 * Serving Flask app 'main'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.101:5000
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 103-093-289
172.18.0.15 - - [11/Sep/2025 21:30:44] "GET /harmonogram/4 HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 21:30:44] "[35m[1mGET /userData/4 HTTP/1.1[0m" 209 -
172.18.0.15 - - [11/Sep/2025 21:30:44] "GET /zadania/4/any HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 21:31:06] "OPTIONS /updateTaskInfo/322 HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 21:31:06] "[35m[1mPATCH /updateTaskInfo/322 HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/backend/main.py", line 191, in updateInfoTask
    cursor.execute(f"UPDATE uzytkownicy SET nazwa={nazwa}, data={data} WHERE ID={ID};")
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ':00-18:00, data=Wed, 10 Sep 2025 17:00:00 GMT WHERE ID=322' at line 1")
172.18.0.15 - - [11/Sep/2025 21:31:11] "GET /harmonogram/4 HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 21:31:11] "GET /zadania/4/any HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 21:31:11] "[35m[1mGET /userData/4 HTTP/1.1[0m" 209 -
172.18.0.15 - - [11/Sep/2025 21:31:40] "OPTIONS /updateTaskInfo/322 HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 21:31:40] "[35m[1mPATCH /updateTaskInfo/322 HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/backend/main.py", line 191, in updateInfoTask
    cursor.execute(f"UPDATE uzytkownicy SET nazwa={nazwa}, data={data} WHERE ID={ID};")
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ':00-18, data=Wed, 10 Sep 2025 17:00:00 GMT WHERE ID=322' at line 1")
172.18.0.15 - - [11/Sep/2025 21:31:42] "GET /harmonogram/4 HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 21:31:42] "[35m[1mGET /userData/4 HTTP/1.1[0m" 209 -
172.18.0.15 - - [11/Sep/2025 21:31:42] "GET /zadania/4/any HTTP/1.1" 200 -
 * Detected change in '/home/rogal/projekty/rogalTasks/backend/main.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 103-093-289
 * Detected change in '/home/rogal/projekty/rogalTasks/backend/main.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 103-093-289
172.18.0.15 - - [11/Sep/2025 21:34:50] "[35m[1mGET /userData/4 HTTP/1.1[0m" 209 -
172.18.0.15 - - [11/Sep/2025 21:34:50] "GET /zadania/4/any HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 21:34:50] "GET /harmonogram/4 HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 21:35:38] "OPTIONS /updateTaskInfo/322 HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 21:35:38] "[35m[1mPATCH /updateTaskInfo/322 HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/backend/main.py", line 192, in updateInfoTask
    cursor.execute(f"UPDATE uzytkownicy SET nazwa={nazwa}, data={data} WHERE ID={ID};")
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ':00-18:00, data=Wed, 10 Sep 2025 17:00:00 GMT WHERE ID=322' at line 1")
172.18.0.15 - - [11/Sep/2025 21:35:41] "OPTIONS /updateTaskInfo/322 HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 21:35:41] "[35m[1mPATCH /updateTaskInfo/322 HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/backend/main.py", line 192, in updateInfoTask
    cursor.execute(f"UPDATE uzytkownicy SET nazwa={nazwa}, data={data} WHERE ID={ID};")
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ':00-18:00, data=Wed, 10 Sep 2025 17:00:00 GMT WHERE ID=322' at line 1")
172.18.0.15 - - [11/Sep/2025 21:39:22] "OPTIONS /updateTaskInfo/322 HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 21:39:22] "[35m[1mPATCH /updateTaskInfo/322 HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/backend/main.py", line 192, in updateInfoTask
    cursor.execute(f"UPDATE uzytkownicy SET nazwa={nazwa}, data={data} WHERE ID={ID};")
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ':00-18:00, data=Wed, 10 Sep 2025 17:00:00 GMT WHERE ID=322' at line 1")
172.18.0.15 - - [11/Sep/2025 21:40:20] "OPTIONS /noweZadanie/4 HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 21:40:20] "[35m[1mPOST /noweZadanie/4 HTTP/1.1[0m" 201 -
172.18.0.15 - - [11/Sep/2025 21:40:20] "[35m[1mGET /userData/4 HTTP/1.1[0m" 209 -
172.18.0.15 - - [11/Sep/2025 21:40:20] "GET /zadania/4/any HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 21:40:20] "GET /harmonogram/4 HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 21:40:24] "GET /harmonogram/4 HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 21:40:24] "GET /zadania/4/any HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 21:40:24] "[35m[1mGET /userData/4 HTTP/1.1[0m" 209 -
172.18.0.15 - - [11/Sep/2025 21:40:32] "OPTIONS /usunZadanie/325 HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 21:40:32] "[35m[1mDELETE /usunZadanie/325 HTTP/1.1[0m" 202 -
172.18.0.15 - - [11/Sep/2025 21:41:36] "OPTIONS /noweZadanie/4 HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 21:41:36] "[35m[1mPOST /noweZadanie/4 HTTP/1.1[0m" 201 -
172.18.0.15 - - [11/Sep/2025 21:41:36] "GET /zadania/4/any HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 21:41:36] "GET /harmonogram/4 HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 21:41:36] "[35m[1mGET /userData/4 HTTP/1.1[0m" 209 -
172.18.0.15 - - [11/Sep/2025 21:41:41] "GET /zadania/4/any HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 21:41:41] "GET /harmonogram/4 HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 21:41:41] "[35m[1mGET /userData/4 HTTP/1.1[0m" 209 -
172.18.0.15 - - [11/Sep/2025 21:41:52] "OPTIONS /usunZadanie/326 HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 21:41:52] "[35m[1mDELETE /usunZadanie/326 HTTP/1.1[0m" 202 -
172.18.0.15 - - [11/Sep/2025 21:41:54] "GET /zadania/4/any HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 21:41:54] "GET /harmonogram/4 HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 21:41:54] "[35m[1mGET /userData/4 HTTP/1.1[0m" 209 -
 * Detected change in '/home/rogal/projekty/rogalTasks/backend/main.py', reloading
Wed, 10 Sep 2025 17:00:00 GMT
Wed, 10 Sep 2025 17:00:00 GMT
Wed, 10 Sep 2025 17:00:00 GMT
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 103-093-289
 * Detected change in '/home/rogal/projekty/rogalTasks/backend/main.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 103-093-289
172.18.0.15 - - [11/Sep/2025 21:45:14] "GET /harmonogram/4 HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 21:45:14] "GET /zadania/4/any HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 21:45:14] "[35m[1mGET /userData/4 HTTP/1.1[0m" 209 -
172.18.0.15 - - [11/Sep/2025 21:45:21] "OPTIONS /updateTaskInfo/322 HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 21:45:21] "[35m[1mPATCH /updateTaskInfo/322 HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/backend/main.py", line 189, in updateInfoTask
    data = datetime.datetime.strptime(data, "%a, %d %b %Y %H:%M:%S %Z")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
172.18.0.15 - - [11/Sep/2025 21:45:23] "GET /harmonogram/4 HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 21:45:23] "[35m[1mGET /userData/4 HTTP/1.1[0m" 209 -
172.18.0.15 - - [11/Sep/2025 21:45:23] "GET /zadania/4/any HTTP/1.1" 200 -
 * Detected change in '/home/rogal/projekty/rogalTasks/backend/main.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 103-093-289
172.18.0.15 - - [11/Sep/2025 21:46:17] "OPTIONS /updateTaskInfo/322 HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 21:46:17] "[35m[1mPATCH /updateTaskInfo/322 HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/backend/main.py", line 193, in updateInfoTask
    cursor.execute(f"UPDATE uzytkownicy SET nazwa={nazwa}, data={data} WHERE ID={ID};")
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ':00-18, data=2025-09-10 17:00:00 WHERE ID=322' at line 1")
172.18.0.15 - - [11/Sep/2025 21:46:19] "GET /harmonogram/4 HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 21:46:19] "GET /zadania/4/any HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 21:46:19] "[35m[1mGET /userData/4 HTTP/1.1[0m" 209 -
 * Detected change in '/home/rogal/projekty/rogalTasks/backend/main.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 103-093-289
172.18.0.15 - - [11/Sep/2025 21:46:55] "GET /harmonogram/4 HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 21:46:55] "GET /zadania/4/any HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 21:46:55] "[35m[1mGET /userData/4 HTTP/1.1[0m" 209 -
172.18.0.15 - - [11/Sep/2025 21:46:58] "OPTIONS /updateTaskInfo/322 HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 21:46:58] "[35m[1mPATCH /updateTaskInfo/322 HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/backend/main.py", line 193, in updateInfoTask
    cursor.execute(f"UPDATE uzytkownicy SET nazwa='{nazwa}', data='{data}' WHERE ID={ID};")
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'nazwa' in 'field list'")
172.18.0.15 - - [11/Sep/2025 21:47:00] "GET /zadania/4/any HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 21:47:00] "[35m[1mGET /userData/4 HTTP/1.1[0m" 209 -
172.18.0.15 - - [11/Sep/2025 21:47:00] "GET /harmonogram/4 HTTP/1.1" 200 -
 * Detected change in '/home/rogal/projekty/rogalTasks/backend/main.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 103-093-289
 * Detected change in '/home/rogal/projekty/rogalTasks/backend/main.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 103-093-289
 * Detected change in '/home/rogal/projekty/rogalTasks/backend/main.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 103-093-289
172.18.0.15 - - [11/Sep/2025 21:47:23] "GET /harmonogram/4 HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 21:47:23] "[35m[1mGET /userData/4 HTTP/1.1[0m" 209 -
172.18.0.15 - - [11/Sep/2025 21:47:23] "GET /zadania/4/any HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 21:47:26] "OPTIONS /updateTaskInfo/322 HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 21:47:26] "[35m[1mPATCH /updateTaskInfo/322 HTTP/1.1[0m" 213 -
172.18.0.15 - - [11/Sep/2025 21:47:28] "[35m[1mGET /userData/4 HTTP/1.1[0m" 209 -
172.18.0.15 - - [11/Sep/2025 21:47:28] "GET /harmonogram/4 HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 21:47:28] "GET /zadania/4/any HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 21:47:34] "OPTIONS /updateTaskInfo/322 HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 21:47:34] "[35m[1mPATCH /updateTaskInfo/322 HTTP/1.1[0m" 213 -
172.18.0.15 - - [11/Sep/2025 21:57:50] "GET /harmonogram/4 HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 21:57:50] "GET /zadania/4/any HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 21:57:50] "[35m[1mGET /userData/4 HTTP/1.1[0m" 209 -
172.18.0.15 - - [11/Sep/2025 21:58:04] "GET /harmonogram/4 HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 21:58:04] "[35m[1mGET /userData/4 HTTP/1.1[0m" 209 -
172.18.0.15 - - [11/Sep/2025 21:58:04] "GET /zadania/4/any HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 21:58:11] "OPTIONS /updateTaskInfo/322 HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 21:58:11] "[35m[1mPATCH /updateTaskInfo/322 HTTP/1.1[0m" 213 -
172.18.0.15 - - [11/Sep/2025 21:58:12] "[35m[1mPATCH /updateTaskInfo/322 HTTP/1.1[0m" 213 -
172.18.0.15 - - [11/Sep/2025 21:58:13] "[35m[1mPATCH /updateTaskInfo/322 HTTP/1.1[0m" 213 -
172.18.0.15 - - [11/Sep/2025 21:58:14] "[35m[1mPATCH /updateTaskInfo/322 HTTP/1.1[0m" 213 -
172.18.0.15 - - [11/Sep/2025 21:58:50] "GET /harmonogram/4 HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 21:58:50] "[35m[1mGET /userData/4 HTTP/1.1[0m" 209 -
172.18.0.15 - - [11/Sep/2025 21:58:50] "GET /zadania/4/any HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 21:58:52] "OPTIONS /updateTaskInfo/322 HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 21:58:52] "[35m[1mPATCH /updateTaskInfo/322 HTTP/1.1[0m" 213 -
172.18.0.15 - - [11/Sep/2025 21:58:53] "[35m[1mPATCH /updateTaskInfo/322 HTTP/1.1[0m" 213 -
172.18.0.15 - - [11/Sep/2025 21:58:55] "[35m[1mPATCH /updateTaskInfo/322 HTTP/1.1[0m" 213 -
172.18.0.15 - - [11/Sep/2025 21:58:57] "[35m[1mPATCH /updateTaskInfo/322 HTTP/1.1[0m" 213 -
172.18.0.15 - - [11/Sep/2025 21:58:59] "OPTIONS /updateTaskInfo/322 HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 21:58:59] "[35m[1mPATCH /updateTaskInfo/322 HTTP/1.1[0m" 213 -
172.18.0.15 - - [11/Sep/2025 22:00:19] "OPTIONS /updateTaskInfo/322 HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 22:00:19] "[35m[1mPATCH /updateTaskInfo/322 HTTP/1.1[0m" 213 -
172.18.0.15 - - [11/Sep/2025 22:00:21] "[35m[1mGET /userData/4 HTTP/1.1[0m" 209 -
172.18.0.15 - - [11/Sep/2025 22:00:21] "GET /zadania/4/any HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 22:00:21] "GET /harmonogram/4 HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 22:05:47] "OPTIONS /updateTaskInfo/322 HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 22:05:47] "[35m[1mPATCH /updateTaskInfo/322 HTTP/1.1[0m" 213 -
172.18.0.15 - - [11/Sep/2025 22:05:49] "[35m[1mPATCH /updateTaskInfo/322 HTTP/1.1[0m" 213 -
172.18.0.15 - - [11/Sep/2025 22:05:56] "OPTIONS /updateTaskInfo/322 HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 22:05:56] "[35m[1mPATCH /updateTaskInfo/322 HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/venv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rogal/projekty/rogalTasks/backend/main.py", line 189, in updateInfoTask
    data = datetime.strptime(data, "%a, %d %b %Y %H:%M:%S %Z")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2025-09-11 19:00:00' does not match format '%a, %d %b %Y %H:%M:%S %Z'
 * Detected change in '/home/rogal/projekty/rogalTasks/backend/main.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 103-093-289
172.18.0.15 - - [11/Sep/2025 22:07:19] "GET /harmonogram/4 HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 22:07:19] "GET /zadania/4/any HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 22:07:19] "[35m[1mGET /userData/4 HTTP/1.1[0m" 209 -
172.18.0.15 - - [11/Sep/2025 22:07:24] "OPTIONS /updateTaskInfo/322 HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 22:07:24] "[35m[1mPATCH /updateTaskInfo/322 HTTP/1.1[0m" 213 -
172.18.0.15 - - [11/Sep/2025 22:07:36] "GET /harmonogram/4 HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 22:07:36] "[35m[1mGET /userData/4 HTTP/1.1[0m" 209 -
172.18.0.15 - - [11/Sep/2025 22:07:36] "GET /zadania/4/any HTTP/1.1" 200 -
 * Detected change in '/home/rogal/projekty/rogalTasks/backend/main.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 103-093-289
172.18.0.15 - - [11/Sep/2025 22:09:58] "GET /harmonogram/4 HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 22:09:58] "[35m[1mGET /userData/4 HTTP/1.1[0m" 209 -
172.18.0.15 - - [11/Sep/2025 22:09:58] "GET /zadania/4/any HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 22:10:02] "OPTIONS /wykonajZadanie/322 HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 22:10:02] "[35m[1mPATCH /wykonajZadanie/322 HTTP/1.1[0m" 203 -
172.18.0.15 - - [11/Sep/2025 22:10:05] "GET /harmonogram/4 HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 22:10:05] "GET /zadania/4/any HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 22:10:05] "[35m[1mGET /userData/4 HTTP/1.1[0m" 209 -
172.18.0.15 - - [11/Sep/2025 22:10:10] "OPTIONS /updateTaskInfo/320 HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 22:10:10] "[35m[1mPATCH /updateTaskInfo/320 HTTP/1.1[0m" 213 -
172.18.0.15 - - [11/Sep/2025 22:10:13] "GET /harmonogram/4 HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 22:10:13] "GET /zadania/4/any HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 22:10:13] "[35m[1mGET /userData/4 HTTP/1.1[0m" 209 -
172.18.0.15 - - [11/Sep/2025 22:11:20] "GET /zadania/4/any HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 22:11:20] "GET /harmonogram/4 HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 22:11:20] "[35m[1mGET /userData/4 HTTP/1.1[0m" 209 -
172.18.0.15 - - [11/Sep/2025 22:12:58] "OPTIONS /noweZadanie/4 HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 22:12:58] "[35m[1mPOST /noweZadanie/4 HTTP/1.1[0m" 201 -
172.18.0.15 - - [11/Sep/2025 22:12:58] "GET /harmonogram/4 HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 22:12:58] "[35m[1mGET /userData/4 HTTP/1.1[0m" 209 -
172.18.0.15 - - [11/Sep/2025 22:12:58] "GET /zadania/4/any HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 22:13:05] "GET /harmonogram/4 HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 22:13:05] "[35m[1mGET /userData/4 HTTP/1.1[0m" 209 -
172.18.0.15 - - [11/Sep/2025 22:13:05] "GET /zadania/4/any HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 22:14:43] "GET /zadania/4/any HTTP/1.1" 200 -
172.18.0.15 - - [11/Sep/2025 22:14:43] "[35m[1mGET /userData/4 HTTP/1.1[0m" 209 -
172.18.0.15 - - [11/Sep/2025 22:14:43] "GET /harmonogram/4 HTTP/1.1" 200 -
